# Generated by Django 5.1.15 on 2026-03-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ticket_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Card')], default='CASH', max_length=10),
        ),
    ]
