# Generated by Django 5.1.15 on 2026-03-25 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shifttemplate_shift_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shifttemplate',
            options={'ordering': ['start_time', 'name']},
        ),
        migrations.AddField(
            model_name='shift',
            name='assigned_cashiers',
            field=models.ManyToManyField(blank=True, related_name='assigned_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
