# Generated by Django 5.1.15 on 2026-03-25 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_shifttemplate_options_shift_assigned_cashiers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttemplate',
            name='default_cashiers',
            field=models.ManyToManyField(blank=True, related_name='shift_templates', to=settings.AUTH_USER_MODEL),
        ),
    ]
