# Generated by Django 5.1.15 on 2026-04-21 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_expense_categories(apps, schema_editor):
    ExpenseCategory = apps.get_model("core", "ExpenseCategory")
    names = (
        "إيجار",
        "مستلزمات ومنتجات",
        "كهرباء وماء",
        "صيانة",
        "رواتب",
        "أخرى",
    )
    for i, name in enumerate(names):
        ExpenseCategory.objects.get_or_create(
            name=name,
            defaults={"sort_order": i, "is_active": True},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_shifttemplate_default_cashiers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('entry_type', models.CharField(choices=[('EXPENSE', 'مصروف'), ('DEPOSIT', 'إيداع')], db_index=True, max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card')], db_index=True, default='CASH', max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_voided', models.BooleanField(db_index=True, default=False)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_entries', to='core.expensecategory')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_entries', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_entries', to='core.shift')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_treasury_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['entry_type', 'created_at'], name='core_treasu_entry_t_14ab14_idx'), models.Index(fields=['is_voided', 'created_at'], name='core_treasu_is_void_6c7088_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='treasury_amount_gt_0')],
            },
        ),
        migrations.RunPython(seed_expense_categories, noop_reverse),
    ]
