# Generated by Django 5.1.15 on 2026-05-11 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_barberprofile_options'),
        ('core', '0009_alter_closeledger_closed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('booking_type', models.CharField(choices=[('WEDDING', 'عرس'), ('EVENT', 'حفل'), ('GROUP', 'مجموعة'), ('CUSTOM', 'مخصص')], max_length=20)),
                ('booking_date', models.DateField(db_index=True)),
                ('booking_time', models.TimeField()),
                ('barbers_count', models.PositiveIntegerField(default=1, help_text='عدد الحلاقين')),
                ('estimated_duration_hours', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='السعر الأساسي', max_digits=12)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, help_text='نسبة الخصم %', max_digits=5)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, help_text='تفاصيل الخدمات المطلوبة')),
                ('special_requests', models.TextField(blank=True, help_text='طلبات خاصة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], db_index=True, default='pending', max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Card')], default='CASH', max_length=10)),
                ('assigned_barbers', models.ManyToManyField(blank=True, related_name='vip_bookings', to='accounts.barberprofile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_vip_bookings', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vip_bookings', to='core.customer')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vip_bookings', to='core.shift')),
            ],
            options={
                'ordering': ['booking_date', 'booking_time'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('receipt_type', models.CharField(choices=[('TICKET', 'وصل تذكرة'), ('VIP_BOOKING', 'وصل حجز VIP'), ('PAYMENT', 'وصل دفع'), ('TREASURY', 'وصل خزنة')], db_index=True, max_length=20)),
                ('receipt_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card')], default='CASH', max_length=10)),
                ('items_description', models.TextField(blank=True, help_text='وصف العناصر/الخدمات')),
                ('note', models.TextField(blank=True, help_text='ملاحظات إضافية')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_receipts', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='core.payment')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='core.shift')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='core.ticket')),
                ('treasury_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='core.treasuryentry')),
                ('vip_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='core.vipbooking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vipbooking',
            index=models.Index(fields=['booking_date', 'status'], name='core_vipboo_booking_ad5a76_idx'),
        ),
        migrations.AddIndex(
            model_name='vipbooking',
            index=models.Index(fields=['customer', 'status'], name='core_vipboo_custome_9f87e8_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_type', 'created_at'], name='core_receip_receipt_a1ed57_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['customer_name'], name='core_receip_custome_2bba03_idx'),
        ),
    ]
