# Generated by Django 5.1.15 on 2026-06-01 08:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_barberprofile_options'),
        ('core', '0010_vipbooking_receipt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberDailyClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('close_date', models.DateField(db_index=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ticket_count', models.PositiveIntegerField(default=0)),
                ('closed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'إغلاق يومي للحلاق',
                'verbose_name_plural': 'إغلاقات يومية للحلاقين',
                'ordering': ['-close_date', '-closed_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'تصنيف خدمة',
                'verbose_name_plural': 'تصنيفات الخدمات',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VIPBarberPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='receipt',
            name='barber_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='receipt',
            name='shift_sequence_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='last_ticket_sequence',
            field=models.PositiveIntegerField(default=0, help_text='آخر رقم تسلسلي للوصل ضمن هذا الشفت'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='core.service'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='shift_sequence',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='رقم تسلسلي للوصل ضمن الشفت (يُطبع على الوصل بدل اسم الزبون)', null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='vipbooking',
            name='booking_type',
            field=models.CharField(choices=[('VIP', 'VIP'), ('WEDDING', 'عرس'), ('EVENT', 'حفل'), ('GROUP', 'مجموعة'), ('CUSTOM', 'مخصص')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('shift_sequence__isnull', False)), fields=('shift', 'shift_sequence'), name='ticket_unique_shift_sequence'),
        ),
        migrations.AddField(
            model_name='barberdailyclose',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_closes', to='accounts.barberprofile'),
        ),
        migrations.AddField(
            model_name='barberdailyclose',
            name='closed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barber_daily_closes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='barberdailyclose',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barber_daily_closes', to='core.shift'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='core.servicecategory'),
        ),
        migrations.AddField(
            model_name='vipbarberpayout',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vip_payouts', to='accounts.barberprofile'),
        ),
        migrations.AddField(
            model_name='vipbarberpayout',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_vip_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vipbarberpayout',
            name='vip_booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_payouts', to='core.vipbooking'),
        ),
        migrations.AlterUniqueTogether(
            name='barberdailyclose',
            unique_together={('barber', 'close_date')},
        ),
    ]
