# Generated by Django 5.1.15 on 2026-06-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_service_categories_shift_sequence_daily_close'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
