# Generated by Django 5.1.15 on 2026-05-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_barberprofile_name_and_optional_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barberprofile',
            options={'ordering': ['name']},
        ),
    ]
